package com.logsik.taman.enums;

public enum TypeOfLeave {
ANNUAL_HOLIDAY,ANNUAL_HOLIDAY_2, ALTERNATIVE_LEAVE, SICK_LEAVE, MATERNITY_LEAVE, MARRIAGE_LEAVE, MOURNING_LEAVE,

NL,NL2,PN,PN2,KP,KP2,	NB,NB2,CHECK_ANNUAL_LEAVE
}
