export const LOAD_UPDATING_LABOUR_ATTENDANCE = 'LOAD_UPDATING_LABOUR_ATTENDANCE';
export const LOAD_LIST_LABOUR_ATTENDANCE_TODAY = 'LOAD_LIST_LABOUR_ATTENDANCE_TODAY';
export const LOAD_LIST_EFFICIENCY = "LOAD_LIST_EFFICIENCY";


